[package]
name = "my-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.3"
dioxus-retrouter = "0.4.0"
karaty-blueprint = "0.2.0"
